{% set name = "argo-workflows" %}
{% set version = "6.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89af123c148b65e0ed9dd309a39676261884255a55f9903913e18dda12cee8ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six
    - python-dateutil
    - urllib3
    - certifi

test:
  imports:
    - argo_workflows
    - argo_workflows.api_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/argo-workflows/
  summary: Client for Argo Workflows
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bchalk101
    - hajapy
