{% set name = "argo-workflows" %}
{% set version = "3.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed4d502c600d0fe7d1609eaa90223bc0212f4e5ef013628238aacc38728d64a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python-kubernetes >=10.0
    - mock
    - python

test:
  imports:
    - argo.workflows
    - argo.workflows.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/argo-workflows/
  summary: Client for Argo Workflows
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
