{% set name = "argo-workflows" %}
{% set version = "6.3.0rc2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 062af6f4dcedafd6badd3f15148ae1c092f68968b2d55a973e3f873fbe650ee5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six
    - python-dateutil
    - urllib3
    - certifi

test:
  imports:
    - argo.workflows
    - argo.workflows.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/argo-workflows/
  summary: Client for Argo Workflows
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hajapy
    - bchalk101
